services:
  redis:
    container_name: "europa_redis"
    image: redis/redis-stack-server:latest
    environment:
      REDIS_ARGS: "--requirepass ${REDIS_PASSWORD} --user redis on >${REDIS_PASSWORD} ~* allcommands --user default off nopass nocommands"
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  database:
    container_name: "europa_postgres"
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: europa_postgres # Fixed the variable name to match the correct environment variable
    ports:
      - "5432:5432"
    healthcheck:
      test:
        ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "europa_postgres"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  europa_api:
    container_name: "europa_api"
    # image: europa
    entrypoint: ["sh", "-c", "wait-for-it redis:6379 && wait-for-it database:5432 -- bun run start"]
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3724:3724"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - redis
      - database
